// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjpiqskjdxsetdtsofzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqcGlxc2tqZHhzZXRkdHNvZnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzYxNzMsImV4cCI6MjA3MDE1MjE3M30.3mf5kQfgt6GbiGsk-uQvum2azPU6ITRWD-pB75DxiaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});